version: '3.8'
services:
  db:
    image: postgres:15
    container_name: scheduling_db
    restart: always
    environment:
      POSTGRES_DB: scheduling_db
      POSTGRES_USER: scheduling_user
      POSTGRES_PASSWORD: scheduling_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: